version: '3.7'
services:

  lunch:
    build:
      dockerfile: ./docker/rails/Dockerfile
      context: .
    restart: always
    dns:
      - '1.1.1.1'

  nginx:
    build:
      dockerfile: ./docker/nginx/Dockerfile
      context: .
    restart: always
    ports:
      - 80:80
      - 443:443
